* more verbose reconf script

diff --git a/reconf b/reconf
--- a/reconf
+++ b/reconf
@@ -9,6 +9,13 @@ fi
 pushd ./ > /dev/null
 cd tools
 echo "Generating source files..."
+perl -e "use Template1" 2> /dev/null
+
+if [ $? != 0 ]; then
+  echo "ERROR: Could not find Template.pm, you need this to autogenerate\
+ parts of the code"
+  exit 1
+fi
 ./generate.sh
 popd > /dev/null
 
